---

name: docker-publish
on:
  push:
    branches: ['master']
    tags: ['v*']

permissions:
  packages: write

jobs:
  docker-publish:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4
        with:
          lfs: true
          show-progress: false

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Publish
        id: taggen
        run: bash ci/docker-gen-tagnames.sh

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.taggen.outputs.docker_build_tags }}

...
